openapi: 3.0.3
info:
  title: es-one-piece-api
  version: 1.0.0
  description:  API to manage characters from One Piece.

paths:
  # Public domains
  /api/v1/characters:
    $ref: './one-piece-api/characters-v1.api.yaml'

components:
  schemas:
    ApiError:
      $ref: './components/ApiError.yaml'
    Character:
      $ref: './components/Character.yaml'
    CharacterBasic:
      $ref: './components/CharacterBasic.yaml'
    Fruit:
      $ref: './components/Fruit.yaml'
    Debut:
      $ref: './components/Debut.yaml'
    Chapter:
      $ref: './components/Chapter.yaml'
    Episode:
      $ref: './components/Episode.yaml'
    Saga:
      $ref: './components/Saga.yaml'
    Race:
      $ref: './components/Race.yaml'
    Haki:
      $ref: './components/Haki.yaml'
    Job:
      $ref: './components/Job.yaml'
    CharacterTitle:
      $ref: './components/CharacterTitle.yaml'
    Affiliation:
      $ref: './components/Affiliation.yaml'
    CharacterAffiliation:
      $ref: './components/CharacterAffiliation.yaml'
  responses:
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'